apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgkxj1413-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgkxj1413-tenant-component
    app.kubernetes.io/part-of: loadgkxj1413-tenant-app
  name: loadgkxj1413-tenant-component
  namespace: loadgkxj1413-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadgkxj1413-tenant-component
status:
  loadBalancer: {}
